apiVersion: 1

datasources:
  - name: RAG-Postgres
    type: postgres
    access: proxy
    uid: rag-db
    isDefault: true
    editable: true
    jsonData:
      sslmode: "disable"
      postgresVersion: 1500
    secureJsonData:
      password: ${GRAFANA_DB_PASSWORD}
    url: ${GRAFANA_DB_HOST}:${GRAFANA_DB_PORT}
    user: ${GRAFANA_DB_USER}
    database: ${GRAFANA_DB_NAME}
